ministryofjustice/laa-crime-applications-adaptor

- .circleci/config.yml
- crime-applications-adaptor/src/main/resources/application.yaml
> LASB-1830  CCI configs

- helm_deploy/laa-crime-applications-adaptor/templates/_environment.tpl
> [LASB-1830] - updated configs

- crime-applications-adaptor/build.gradle
Updating jsonschema2dataclass from 4.x to 6.0.0
> Updating jsonschema2dataclass version

- crime-applications-adaptor/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/controller/CrimeApplicationController.java
- crime-applications-adaptor/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/service/EformStagingService.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/controller/CrimeApplicationControllerTest.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/integration/CrimeApplicationIntegrationTest.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/service/EformStagingServiceTest.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/testutils/MockWebServerStubs.java
- crime-applications-adaptor/src/test/resources/data/eformstaging/EformStagingResponse_CreatedByHub_6000310.json
[LASB-2136](https://dsdmoj.atlassian.net/browse/LASB-2136)
[LASB-2136]: https://dsdmoj.atlassian.net/browse/LASB-2136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2136] Insert a dummy entry if CA datastore call is success

- crime-applications-adaptor/build.gradle
- crime-applications-adaptor/src/main/resources/application.yaml
> LASB-1972 - get Prometheus working.

- .circleci/config.yml
[/LASB-2211](https://dsdmoj.atlassian.net/browse/LASB-2211)
> [LASB-2211] Updating Short lived credentials configs

- crime-applications-adaptor/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/CaseDetailsMapper.java
- crime-applications-adaptor/src/main/resources/schemas/crimeapplicationsadaptor/common/caseDetails.json
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/CaseDetailsMapperTest.java
- crime-applications-adaptor/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_default.json
[LASB-2248](https://dsdmoj.atlassian.net/browse/LASB-2248)
[LASB-2248]: https://dsdmoj.atlassian.net/browse/LASB-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2248] populate Appeal lodged date changes

- crime-applications-adaptor/build.gradle
[LASB-2811](https://dsdmoj.atlassian.net/browse/LASB-2811)
Upgrade Sentry version
[LASB-2811]: https://dsdmoj.atlassian.net/browse/LASB-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2811] Upgrade Sentry version

- crime-applications-adaptor/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/client/MaatCourtDataApiClient.java
- crime-applications-adaptor/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/controller/CrimeApplicationController.java
- crime-applications-adaptor/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/service/EformStagingService.java
- crime-applications-adaptor/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/service/EformsHistoryService.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/controller/MaatApplicationExternalInternalControllerTest.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/integration/MaatApplicationExternalInternalIntegrationTest.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/service/EformStagingServiceTest.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/service/EformsHistoryServiceTest.java
- crime-applications-adaptor/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/testutils/MockWebServerStubs.java
[LASB-2861](https://dsdmoj.atlassian.net/browse/LASB-2861)
[LASB-2861]: https://dsdmoj.atlassian.net/browse/LASB-2861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LASB-2861] Passing user id for application tracking

- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/InvestmentMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/NationalSavingsCertificateMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/PropertyMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/SavingMapper.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3219)
> LASB-3219 - implemented switches rather than conditions.

- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/factory/PoundSterling.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/BenefitsMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/InvestmentMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/NationalSavingsCertificateMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/OtherIncomeMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/OutgoingsMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/PremiumBondMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/PropertyMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/SavingMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/TrustFundMapper.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/factory/PoundSterlingTest.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/BenefitsMapperTest.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/CapitalEquityMapperTest.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/OtherIncomeMapperTest.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/OutgoingsMapperTest.java
- crime-applications-adaptor/application/src/test/resources/data/crimeapplicationsadaptor/CrimeApplication_6000308.json
- crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplicationNoHomeAddress_toBeMapped.json
- crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_6000308.json
- crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_unemployed.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3224)
Update the mappers to convert currencies to pounds for MAAT as Crime Apply provides them in pence.
> [LASB-3224] Currency conversion

- crime-applications-adaptor/api-tests/src/test/resources/testdata/expectedresponses/10000340_capital_equity.json
- crime-applications-adaptor/api-tests/src/test/resources/testdata/expectedresponses/10000390_means_with_partner.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3422)
> [LASB-3422] updating API tests

- crime-applications-adaptor/api-tests/build.gradle
- crime-applications-adaptor/application/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3496)
> [LASB-3496] Updating schema version 1.3.2

- .circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3206)
This PR adds the circle-ci integration with slack and reports: 
When main fails api tests
When main fails the compile
When any branch successfully deploys
When main fails to deploy
> Lasb 3206/circle ci slack integration

- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/InitialMeansAssessmentMapper.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/InitialMeansAssessmentMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3501)
Mapping Initial Assessment Notes
> [LASB-3501] Mapping Initial Assessment Notes

- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/InitialMeansAssessmentMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/ManageWithoutIncomeMapper.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/InitialMeansAssessmentMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3501)
Without Income mapping changes
> [LASB-3501] Without Income mapping changes

- crime-applications-adaptor/api-tests/build.gradle
- crime-applications-adaptor/application/build.gradle
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/CrimeApplicationResultMapper.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3610)
Update to new crime commons schema version with updated jsontopojo config. This schema update means all empty/ null fields will be serialised and included on the response. 
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
> Lasb 3610/update empty response

- crime-applications-adaptor/api-tests/build.gradle
- crime-applications-adaptor/application/build.gradle
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/CrimeApplicationResultMapper.java
- crime-applications-adaptor/application/src/main/java/uk/gov/justice/laa/crime/applications/adaptor/model/RepOrderState.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/mapper/crimeapply/CrimeApplicationResultMapperTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3784)
Added the cc_rep_decision to the response sent to CA for ATIS 
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
> Add cc_rep_decision to CA response

- crime-applications-adaptor/api-tests/src/test/resources/testdata/crimeapply/crimeapplytestdata10000340.json
- crime-applications-adaptor/api-tests/src/test/resources/testdata/crimeapply/crimeapplytestdata10000987.json
- crime-applications-adaptor/api-tests/src/test/resources/testdata/crimeapply/crimeapplytestdata10000988.json
- crime-applications-adaptor/api-tests/src/test/resources/testdata/expectedresponses/10000340_capital_equity.json
- crime-applications-adaptor/api-tests/src/test/resources/testdata/expectedresponses/10000987_passported.json
- crime-applications-adaptor/api-tests/src/test/resources/testdata/expectedresponses/10000988_non_passported.json
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/config/MockServicesConfiguration.java
- crime-applications-adaptor/application/src/test/java/uk/gov/justice/laa/crime/applications/adaptor/util/MaatApplicationExternalInternalUtilTest.java
- crime-applications-adaptor/application/src/test/resources/application.yaml
- crime-applications-adaptor/application/src/test/resources/data/crimeapplicationsadaptor/CrimeApplication_6000308.json
- crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_10000331.json
- crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_6000288.json
- crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_6000308.json
- crime-applications-adaptor/application/src/test/resources/data/criminalapplicationsdatastore/MaatApplication_toBeMapped.json
- crime-applications-adaptor/application/src/test/resources/data/expected/crimeapplication/CrimeApplication_mapped.json
Updated test client secrets - pretty confident this was a "fake" secret anyway but have updated just to be sure and to make it obvious. 
Replaced potentially real provider email addresses
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
> Remove sensitive data

- .circleci/config.yml
- .github/workflows/codeql-analysis.yml
- README.md
- crime-applications-adaptor/Dockerfile
- crime-applications-adaptor/Dockerfile.api-tests
- crime-applications-adaptor/api-tests/build.gradle
- crime-applications-adaptor/application/build.gradle
- crime-applications-adaptor/build.gradle
- crime-applications-adaptor/gradle/wrapper/gradle-wrapper.properties
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4180)
- Upgraded to Java 21.
- Upgraded Gradle to version 8.14.2.
- Upgraded JaCoCo to version 0.8.13.
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
> LASB-4180 - Upgrade to Java 21
